site_name: 安全运营之路

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  icon:
  logo: 'assets/logo_white.png'
  favicon: 'assets/favicon.ico'


extra:
  search:
    language: 'jp'